urls.py
from django.contrib.auth import views
from django.urls import path

from .forms import UserLoginForm, ResetPasswordForm, ChangePasswordForm
from .views import logout_view, SignUpView, success_register, token_sent, missing_token, lost_username, activate_account, otp, otp_new_challenge, otp_totp_qr_code, otp_totp_check, otp_totp_settings, username_sent


urlpatterns = [
    path(
        'login/',
        views.LoginView.as_view(
            template_name="auth-login.html",
            authentication_form=UserLoginForm
            ),
        name='login'
    ),
    path('logout/', logout_view, name='logout'),
    path('change-password/', views.PasswordChangeView.as_view(template_name="change_password_form.html", form_class=ChangePasswordForm)),
    path('reset-password/', views.PasswordResetView.as_view(template_name="password_reset_form.html", form_class=ResetPasswordForm), name="password_reset"),
    path('reset-password-sent/', views.PasswordResetView.as_view(template_name="password_reset_sent.html"), name="password_reset_done"),
    path('reset-password-confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name="reset_password_form.html"), name='password_reset_confirm'),
    path('reset-password-complete/', views.PasswordResetCompleteView.as_view(template_name="password_reset_complete.html"), name="password_reset_complete"),
    path("register/", SignUpView.as_view(), name="register"),
    path("missing-token/", missing_token, name="missing_token"),
    path("lost-username/", lost_username, name="lost_username"),
    path("token-sent/", token_sent, name="token_sent"),
    path("token-resent/", token_sent, name="token_resent"),
    path("username-sent/", username_sent, name="username_sent"),
    path("successregister/", success_register, name="success_register"),
    path('activate/<token>/',  activate_account, name='activate_account'),
    path('otp/new_challenge/', otp_new_challenge, name='otp_new_challenge'),
    path('otp/settings/', otp_totp_settings, name='otp_totp_settings'),
    path('otp/totp_qr/', otp_totp_qr_code, name='otp_totp_qr_code'),
    path('otp/totp_check/', otp_totp_check, name='otp_totp_check'),
    path('otp/', otp, name='otp'),
]

forms.py
import logging

from django.contrib.auth.forms import AuthenticationForm, UsernameField, PasswordResetForm, UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from .models import UserValidation, BlackList
from .fields import CaptchaField

_logger = logging.getLogger(__name__)


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': ''
        }))
    captcha = CaptchaField()

    # def clean_username(self):
    #     data = self.cleaned_data["username"]
    #     if UserValidation.objects.filter(owner_uid__username=data).filter(owner_uid__is_active=False).count()==1:
    #         raise ValidationError(_("This account is not activated."))
    #     return data


class ResetPasswordForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(ResetPasswordForm, self).__init__(*args, **kwargs)

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))


class ChangePasswordForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)

    old_password = forms.CharField(label=_('Old password'), widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    new_password1 = forms.CharField(label=_('New password'), widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    new_password2 = forms.CharField(label=_('Repeat new password'), widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    

class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    captcha = CaptchaField()
    
    def clean_email(self):
        data = self.cleaned_data["email"]
        if BlackList.objects.filter(email=data).count()>0:
            raise ValidationError(_("The account linked to this email is waiting activation."))
        if UserValidation.objects.filter(owner_uid__email=data).filter(owner_uid__is_active=False).count()==1:
            raise ValidationError(_("The account linked to this email is waiting Activation."))
        if User.objects.filter(email=data).count()>0:
            raise ValidationError(_("An account is already linked to this email address."))
        return data
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_active = False
        if commit:
            user.save()
        uv = UserValidation.objects.create(owner_uid=user)
        if not uv.send_mail():
            _logger.error("Impossible to send email, drop user validation. %s")
            uv.owner_uid.delete()
            uv.delete()
            raise Exception("Impossible to create user")
        return user


class MissingTokenForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    
    def clean_email(self):
        data = self.cleaned_data["email"]
        if UserValidation.objects.filter(owner_uid__email=data).count()==0:
            raise ValidationError(_("Either your account is already validated, or you've not registered."))
        return data
    

class LostUsernameForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={
            'class': 'form-control', 
            'placeholder': ''
        }))
    
    def clean_email(self):
        data = self.cleaned_data["email"]
        if User.objects.filter(email=data).count()==0:
            raise ValidationError(_("No account found for this email."))
        return data

templates/auth-base.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% load random_backgrounds %}

<!DOCTYPE html>
  <html lang="en">
    <head>   
        
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
    
        <title>BeamZe - {% block subtitle %}{% endblock %}</title>
        <link rel="shortcut icon" type="image/png" href="/static/favicon.ico"/>
        <link rel="canonical" href="https://{{ request.get_host }}{% block canonicalurl %}{{ request.get_full_path }}{% endblock %}"> 

        {% include "css.html" %}
        <link rel="stylesheet" href="/static/src/css/auth.css"/>

    </head>
        
    <body id="page-top" style="background-image: url('{% random_background %}')">      
      {% include "js.html" %}
          <main class="d-flex w-100">
            <div class="container d-flex flex-column">
              <div class="row vh-100">
                <div class="col-sm-12 col-md-12 col-lg-12 mx-auto d-table h-100">
                  <div class="d-table-cell align-middle">

                    <div class="card-group">
                      <div class="card">
                        <div class="card-body beamzgrey">
                          <div class="text-center mt-4">
                            <h1 class="h2">{% block headercontent %}{% endblock %}</h1>
                          </div>        
                          
                          <a href="/{{ LANGUAGE_CODE }}/"><img src="/static/img/Logo.png" class="img-fluid" alt="BeamZe Logo" style="margin: 0 auto; display: block;"/></a>

                          <div class="text-center mt-4">
                            <p class="lead">
                              {% block introcontent %}{% endblock %}
                            </p>
                          </div>

                          <form action="{% url 'set_language' %}" method="post">{% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <select name="language"  class="form-select" data-width="fit" onchange="this.form.submit()">
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                                      {% if language.code == 'en' %}🇬🇧&emsp;{% endif %}
                                      {% if language.code == 'fr' %}🇫🇷&emsp;{% endif %}
                                      {% if language.code == 'de' %}🇩🇪&emsp;{% endif %}
                                      {% if language.code == 'nl' %}🇳🇱&emsp;{% endif %}
                                      {{ language.name_local }} 
                                    </option>
                                {% endfor %}
                            </select>
                          </form>
                        </div>
                      </div>
                    
                      <div class="card">
                        <div class="card-body">
                            <div class="m-sm-4">
                              <form method="post">
                                {% block formcontent %}{% endblock %}
                              </form>
                            </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
          </div>
        </main>
    </body>
</html>

templates/auth-login.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block canonicalurl %}/login/{% endblock %}
{% block subtitle %}{% trans "Sign in" %}{% endblock %}

{% block headercontent %}{% trans "Welcome back" %}{% endblock %}
{% block introcontent %}{% trans "Sign in to your account to continue" %}{% endblock %}

{% block formcontent %}
	{% if user.is_authenticated %}
		<div class="alert alert-success" role="alert">
			<center>{% trans "You are already logged in as" %} {{ user.username }}</center>
			<br/>
			<div class="d-flex justify-content-between">
				<a href="{% url 'logout' %}" class="btn btn-primary float-start">{% trans "Logout" %}</a>
				<a href="/app" class="btn btn-success float-right">{% trans "Dashboard" %}</a>
			</div>
		</div>
	{% endif %}

	{{ form.non_field_errors }}
	{% csrf_token %}
	<div class="form-group mb-3">
		
		<label class="form-label" for="{{ form.username.id_for_label }}">{% trans "Username" %}:</label>
		{{ form.username }}
		{{ form.username.errors }}
		<small>
			{% trans "Forgot username" %}? <a href="{% url 'lost_username' %}">{% trans "Recover username" %}</a>
		</small>

	</div>
	<div class="form-group mb-3">
		
		<label class="form-label" for="{{ form.password.id_for_label }}">{% trans "Password" %}:</label>
		{{ form.password }}
		{{ form.password.errors }}
		<small>
			{% trans "Forgot password" %}? <a href="{% url 'password_reset' %}">{% trans "Reset Password" %}</a>
		</small>
	</div>
	
	<div class="form-group mb-3 text-center">
		{{ form.captcha }}
	</div>

	<div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Login" %}</button>
	</div>
	<div class="text-center mt-3">
		{% trans "Don't have an account?" %} <a href="{% url 'register' %}">{% trans "Join Now" %}</a>
	</div>


{% endblock %}


templates/auth-otp.html
{% extends "auth-base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block subtitle %}{% trans "OTP Password" %}{% endblock %}

{% block headercontent %}{% trans "Welcome back" %}{% endblock %}
{% block introcontent %}{% trans "2FA authentification" %}{% endblock %}

{% block formcontent %}
    <script>
        function request_new_challenge() {
            fetch('/{{ LANGUAGE_CODE }}/otp/new_challenge/', {
                credentials: "same-origin",
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    'Accept': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
            })
        }
    </script>

    <div class="alert alert-success" role="alert">
        <center>
            {% trans "You're accessing a section which requires 2 factors authentification." %}
            {% if device.type == 'totp' %}{% trans "Enter the 6 digits code from your authentification application." %}{% endif %}
            {% if device.type == 'email' %}{% trans "We've sent an email with the 6 digits code." %}{% endif %}
        </center>
    </div>

	{{ form.non_field_errors }}
	{% csrf_token %}

    
    <div class="form-group mb-3">
        {% if error_msg %}
            <div class="alert alert-danger" role="alert">
                {{ error_msg }}
            </div>
        {% endif %}
        
        <center>
            {{ form.otp_token }}
        </center>

        {% if form.otp_token.errors %}
            <div class="alert alert-danger" role="alert">
                {{ form.otp_token.errors }}
            </div>
        {% endif %}

	</div>

    <div class="submit-row text-center mt-3">
        <button type="submit" class="btn btn-lg btn-primary">{% trans "Authenticate" %}</button>
    </div>
    {% if device.type == 'email' %}<br/><center>{% trans "Email not received ?" %} <a href="#" onclick="request_new_challenge()">{% trans "Re-send code" %}</a></center>{% endif %}

{% endblock %}


templates/auth-register.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block canonicalurl %}/register/{% endblock %}
{% block subtitle %}{% trans "Register" %}{% endblock %}

{% block headercontent %}{% trans "Welcome" %}{% endblock %}
{% block introcontent %}{% trans "Register to access the application" %}{% endblock %}

{% block formcontent %}

	{{ form.non_field_errors }}

    {% if extra_error %}
        <div class="alert alert-danger" role="alert">
            {{ extra_error }}
        </div>
    {% endif %}

    {% csrf_token %}

    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.username.id_for_label }}">{% trans "Username" %}:</label>
		{{ form.username }}
		{% if form.username.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.username.errors }}
        </div>
        {% endif %}
	</div>
    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.email.id_for_label }}">{% trans "Email" %}:</label>
		{{ form.email }}
		{% if form.email.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.email.errors }}
        </div>
        {% trans "Lost username?" %} <a href="{% url 'lost_username' %}" >{% trans "Recover it" %}</a><br/>
        {% trans "Missed activation email?" %} <a href="{% url 'missing_token' %}">{% trans "Resend it" %}</a>
        {% endif %}
	</div>
    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.password1.id_for_label }}">{% trans "Password" %}:</label>
		{{ form.password1 }}
		{% if form.password1.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.password1.errors }}
        </div>
        {% endif %}
	</div>
    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.password2.id_for_label }}">{% trans "Repeat password" %}:</label>
		{{ form.password2 }}
		{% if form.password2.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.password2.errors }}
        </div>
        {% endif %}
	</div>
    <div class="form-group mb-3 text-center">
        {{ form.captcha }}
    </div>


    <div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Sign up" %}</button>
	</div>

    <div class="text-center mt-3">
		{% trans "Already have an account?" %} <a href="{% url 'login' %}">{% trans "Login" %}</a>
        {% if form.errors %}
        <br/>
        {% trans "Searching for account validation email?" %}" <a href="{% url 'missing_token' %}">{% trans "Resend it" %}</a>
        {% endif %}
	</div>

{% endblock %}


templates/change_password_form.html
{% extends "auth-base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block subtitle %}{% trans "Change password" %}{% endblock %}

{% block headercontent %}{% trans "Need a new password?" %}{% endblock %}

{% block introcontent %}{% trans "Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly." %}{% endblock %}

{% block formcontent %}
    {{ form.non_field_errors }}
    {% csrf_token %}
    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.old_password.id_for_label }}">{% trans "Old password" %}:</label>
		{{ form.old_password }}
		{% if form.old_password.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.old_password.errors }}
        </div>
        {% endif %}
	</div>
    
    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.new_password1.id_for_label }}">{% trans "New password" %}:</label>
		{{ form.new_password1 }}
		{% if form.new_password1.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.new_password1.errors }}
        </div>
        {% endif %}
	</div>

    <div class="form-group mb-3">
		<label class="form-label" for="{{ form.new_password2.id_for_label }}">{% trans "Repeat new password" %}:</label>
		{{ form.new_password2 }}
		{% if form.new_password2.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.new_password2.errors }}
        </div>
        {% endif %}
	</div>

    <div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Change password" %}</button>
		<a href="/{{ LANGUAGE_CODE }}/" class="btn btn-lg btn-light">{% trans "Cancel" %}</a>
	</div>
{% endblock %}


templates/lost-username.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block subtitle %}{% trans "Lost username" %}{% endblock %}

{% block headercontent %}{% trans "Enter your email adress" %}{% endblock %}

{% block introcontent %}{% trans "Lost your username? Enter your email address and we'll send you a reminder." %}{% endblock %}

{% block formcontent %}
    {{ form.non_field_errors }}
    {% csrf_token %}
   
    {% if form.email.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.email.errors }}
        </div>
    {% endif %}
    {% if extra_error %}
        <div class="alert alert-danger" role="alert">
            {{ extra_error }}
        </div>
    {% endif %}
    <div class="form-group mb-3">
        <label for="id_email">{% trans "Email adress" %}:</label>
        <input class="form-control" type="email" id="id_email" name="email" value="">
    </p>

    <div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Remind me my username" %}</button>
	</div>
    
{% endblock %}

templates/mail_activation.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="font-family: sans-serif;">
        <div style="display: block; margin: auto; max-width: 600px;" class="main">
            <h1 style="font-size: 18px; font-weight: bold; margin-top: 20px">
                {% trans "Congrats for registering your BeamZe account." %}
            </h1>
            <p>{% trans "Here is the link to activate the account" %}: <a href='https://beamze.app/activate/{{ token }}/'>https://beamze.app/activate/{{ token }}/</a></p>
        </div>
        <style>
            .main { background-color: white; }
            a:hover { border-left-width: 1em; min-height: 2em; }
        </style>
    </body>
</html>

templates/mail_username.html
{% load i18n %}
<!doctype html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    </head>
    <body style="font-family: sans-serif;">
        <div style="display: block; margin: auto; max-width: 600px;" class="main">
            <h1 style="font-size: 18px; font-weight: bold; margin-top: 20px">
                {% trans "Recover your BeamZe username." %}
            </h1>
            <p>{% trans "Here is your username" %}: {{ login }}</p>
            <p>You can use it to login <a href='https://beamze.app/login/'>https://beamze.app/login/</a></p>
        </div>
        <style>
            .main { background-color: white; }
            a:hover { border-left-width: 1em; min-height: 2em; }
        </style>
    </body>
</html>

templates/missing-token.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block subtitle %}{% trans "Validation email not received" %}{% endblock %}

{% block headercontent %}{% trans "Enter your email adress" %}{% endblock %}

{% block introcontent %}{% trans "If you've not received our activation email, we'll send it again to activate your account" %}{% endblock %}

{% block formcontent %}
    {{ form.non_field_errors }}
    {% csrf_token %}
   
    {% if form.email.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.email.errors }}
        </div>
    {% endif %}
    {% if extra_error %}
        <div class="alert alert-danger" role="alert">
            {{ extra_error }}
        </div>
    {% endif %}
    <div class="form-group mb-3">
        <label for="id_email">{% trans "Email adress" %}:</label>
        <input class="form-control" type="email" id="id_email" name="email" value="">
    </p>

    <div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Send my activation email" %}</button>
	</div>
    
{% endblock %}

templates/password_reset_sent.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block subtitle %}{% trans "Email sent" %}{% endblock %}

{% block headercontent %}{% trans "Password reset instructions sent" %}{% endblock %}

{% block introcontent %}{% trans "We've emailed you instructions for setting your password. You should receive the email shortly!" %}{% endblock %}

templates/reset_password_form.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block subtitle %}{% trans "Enter new password" %}{% endblock %}

{% block headercontent %}{% trans "Enter new password" %}{% endblock %}

{% block introcontent %}{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}{% endblock %}

{% block formcontent %}
    {{ form.non_field_errors }}
    {% csrf_token %}
   
    {% if form.new_password1.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.new_password1.errors }}
        </div>
    {% endif %}
    <div class="form-group mb-3">
        <label for="id_new_password1">{% trans "New password" %}:</label>
        <input class="form-control" type="password" id="id_new_password1" name="new_password1" value="">
    </p>
    {% if form.new_password2.errors %}
        <div class="alert alert-danger" role="alert">
            {{ form.new_password2.errors }}
        </div>
    {% endif %}
    <div class="form-group mb-3">
        <label for="id_new_password2">{% trans "Confirm password" %}:</label>
        <input class="form-control" type="password" id="id_new_password2" name="new_password2" value="">
    </div>

    <div class="text-center mt-3">
		<button type="submit" class="btn btn-lg btn-primary">{% trans "Reset my password" %}</button>
	</div>
{% endblock %}


templates/success-register.html
{% extends "auth-base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block subtitle %}{% trans "Register" %}{% endblock %}

{% block headercontent %}{% trans "Welcome" %}{% endblock %}
{% block introcontent %}{% trans "Successful register" %}{% endblock %}

{% block formcontent %}

	<p> {% trans "You're now registered as a free user." %}" <a href="/{{ LANGUAGE_CODE }}/login">{% trans "Login" %}</a> {% trans "to continue." %}</p>
	<p> {% trans "To analyse structures, you'll need a professional or student subscription. You can request it through" %} <a href="/{{ LANGUAGE_CODE }}/app/subscription/">{% trans "your portal" %}</a>. </p>
	<p> {% trans "Member of an organisation? Ask your admin to add your account in the org." %}</p>

{% endblock %}


templates/token-sent.html
{% extends "auth-base.html" %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block subtitle %}{% trans "Token sent" %}{% endblock %}

{% block headercontent %}{% trans "Welcome" %}{% endblock %}
{% block introcontent %}{% trans "Successfully registered" %}{% endblock %}

{% block formcontent %}

	<p> {% trans "You're now registered, but you must confirm your email to" %} <b>{% trans "activate" %}</b> {% trans "your account" %}.</p>
    <p> {% trans "We've sent an email with a confirmation link. Not received? Check your spam box." %}</p>
    <p> {% trans "Still not received?" %} <a href='/{{ LANGUAGE_CODE }}/missing-token/' class="btn btn-primary">{% trans "Send activation mail" %}</a></p>

{% endblock %}

templates/username-sent.html
{% extends "auth-base.html" %}
{% load i18n %}

{% block subtitle %}{% trans "Username sent" %}{% endblock %}

{% block headercontent %}{% trans "Welcome" %}{% endblock %}
{% block introcontent %}{% trans "Successfully sent username reminder email" %}{% endblock %}

{% block formcontent %}

    <p> {% trans "We've sent an email with your username. Not received? Check your spam box." %}</p>
    <p> <a href="{% url 'login' %}" class="btn btn-primary">{% trans "Login" %}</a></p>

{% endblock %}